services:
  frontend:
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    command: sleep infinity


  backend:
    profiles:
      - avoid

  backend-init:
    profiles:
      - avoid

  db:
    profiles:
      - avoid

  pgadmin:
    profiles:
      - avoid