services:
    
  backend:
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace
    command: sleep infinity
    # depends_on: !reset []


  # frontend:
  #   profiles:
  #     - avoid

