services:
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
        NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID: ${NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID}
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace
    command: sleep infinity
    
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace
    command: sleep infinity