services:
  frontend:
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace
    build: 
      context: ./frontend
      dockerfile: Dev.Dockerfile
    command: sleep infinity
    user: root
